name: TestRail Integration

on:
  push:
    branches:
      - main
      - testrail_v3
  pull_request:
    branches:
      - main
      - testrail_v3

jobs:
  testrail-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run TestRail Integration Script
      run: node index.js
      env:
        TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
        TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
        TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
        

    - name: Send Slack Notification
      run: |
        echo "SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL"  # Webhook URL 출력하여 확인
        node -e "
          const axios = require('axios');
          const slackMessage = {
            text: 'Test Run Details:\\nName: TestRunName\\nPassed: 4\\nFailed: 1\\nBlocked: 0\\nURL: TestRunURL'
          };
          console.log('Sending Slack message to:', process.env.SLACK_WEBHOOK_URL);  # Webhook URL 로그 출력
          axios.post(process.env.SLACK_WEBHOOK_URL, slackMessage)
            .then(() => console.log('Message sent to Slack'))
            .catch(error => console.error('Error sending message to Slack:', error));
        "
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # 환경 변수로 SLACK_WEBHOOK_URL 전달