name: TestRail Integration

on:
  push:
    branches:
      - main
      - testrail_v3
  pull_request:
    branches:
      - main
      - testrail_v3

jobs:
  testrail-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run TestRail Integration Script
      run: node index.js
      env:
        TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
        TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
        TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}